### ISSUE TITLE
Web services are not started due to missing server.xml

### ISSUE THREAD

**Issue by kallu** [aws-quickstart/quickstart-ibm-mq#16]
Fresh EC2 started by auto-scaling has below error in /var/mqm/web/installations/Installation1/servers/defaultServer/logs/status.log. Nothing is responding on instance port 9080 or 9443.

```
com.ibm.ws.kernel.boot.LocationException: Not Found /var/mqm/web/installations/Installation1/servers/defaultServer/server.xml
	at com.ibm.ws.kernel.boot.BootstrapConfig.verifyProcess(BootstrapConfig.java:892)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:98)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
                 Java home:  /opt/mqm/java/jre64/jre
              Install root:  /opt/mqm/web/
          System libraries:  /opt/mqm/web/lib/
                 User root:  /var/mqm/web/installations/Installation1/
                    Config:  /var/mqm/web/installations/Installation1/servers/defaultServer/
                    Output:  /var/mqm/web/installations/Installation1/servers/defaultServer/


arg0=defaultServer
arg1=--pid=
arg2=--status
exit=23

                 Java home:  /opt/mqm/java/jre64/jre
              Install root:  /opt/mqm/web/
          System libraries:  /opt/mqm/web/lib/
                 User root:  /var/mqm/web/installations/Installation1/
                    Config:  /var/mqm/web/installations/Installation1/servers/defaultServer/
                    Output:  /var/mqm/web/installations/Installation1/servers/defaultServer/
```

**Comment by kallu** [comment]
While mqweb is installed and running it doesn't seem to be fully configured. Following instructions from https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.con.doc/q132130_.htm and running the command below I got web console and API responding.

```
$ sudo su mqm
$ setmqweb properties -k httpHost -v "*"
$ dspmqweb status
MQWB1124I: Server 'mqweb' is running.
URLS:
  https://ip-xxx-xxx-xxx-xxx.AWS-REGION.compute.internal:9443/ibmmq/console/
  https://ip-xxx-xxx-xxx-xxx.AWS-REGION.compute.internal:9443/ibmmq/rest/v1/

$ setmqweb properties -k mqRestMftEnabled -v true
$ setmqweb properties -k mqRestMftCoordinationQmgr -v QM1
```

**Comment by kallu** [comment]
Here is PR for fixing this in configure.sh
https://github.com/aws-quickstart/quickstart-ibm-mq/pull/17
